dist: trusty
language: rust
rust:
  - nightly
before_install:
    - sudo apt-get install libssh2-1-dev
env:
  - _CMD=test
  - _CMD=clippy
script:
  - make $_CMD
notifications:
  email:
    on_failure: change
    on_success: change
