language: rust
cache: cargo
rust:
  - nightly
before_install:
    - sudo apt-get install libssh2-1-dev
script:
  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; make cargo_update; fi
  - make cargo_update
notifications:
  email:
    on_failure: change
    on_success: change
