dist: trusty
language: rust
rust:
  - nightly
before_install:
    - sudo apt-get update
    - virtualenv ./depclose
    - source ./depclose/bin/activate
    - pip install --upgrade pip
    - pip install -r ./tests/depclose-integration/requirements.txt
    - |
        LOCAL="~/.local" && export PATH=$LOCAL/bin:$PATH &&
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
        tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
        cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && make && make install && cd ../..

addons:
  apt:
    packages:
      # to fix Permission denied when installing pip packages
      # b/c Travis will use system-wide Python when language != python
      - python-virtualenv
      # dependencies for bdcs-api-rs
      - libssh2-1-dev
      # used by Makefile
      - realpath
      # dependencies of kcov, used by coverage
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - libiberty-dev

script:
  - make travis-ci
after_script:
  - |
      ls -l target/debug &&
      for file in target/debug/*-*; do
        if [[ "${file: -2}" != ".d" ]]; then
          mkdir -p "target/kcov/$(basename $file)";
          kcov --include-path=./src --verify "target/kcov/$(basename $file)" "$file";
        fi;
      done &&
      kcov --coveralls-id=$TRAVIS_JOB_ID --merge target/kcov target/kcov/*
notifications:
  email:
    on_failure: change
    on_success: change
